
# Base URL
@baseUrl = http://localhost:3000

### Root endpoint
GET {{baseUrl}}/

//Metrics endpoint
###
GET {{baseUrl}}/metrics

//API DOCUMENTATION ENDPOINT
###
GET {{baseUrl}}/api


# ======AUTH TESTING ENDPOINTS=====

### Create a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john@example.com",
  "phone_number": "0712345678",
  "password": "123456",
  "user_type": "customer"
}

### Admin Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjE3Njg1ODYsImV4cCI6MTc2MTc3MjE4Nn0.isLAWqZoeL4o-_Xh-K3y5IyNRSyB--SsaocO5_N8Ry8

{
  "email": "Micheal@outlook.com",
  "password": "adminpass"
}

### user login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "denis@gmail.com",
  "password": "password123"
}



### Update user
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "first_name": "denis",
  "last_name": "kathuri",
  "email": "denis@gmail.com",
  "phone_number": "0723356478",
  "password": "password123"
}



# ### Unhashed Users
# POST {{baseUrl}}/api/auth/login
# Content-Type: application/json

# {
#   "email": "brian@gmail.com",
#   "password": "password123"
# }


###
# USER ENDPOINTS

### Get all users
GET http://localhost:3000/api/MenuItem
Authorization: Bearer 


### Get user by ID
GET {{baseUrl}}/api/users/2



### Delete user
DELETE {{baseUrl}}/api/users/5

###Restaurant checking End points

###Get all Restaurants

GET {{baseUrl}}/api/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE4MDc0NTYsImV4cCI6MTc2MTgxMTA1Nn0.H8ELLmNAbUOMc-qpD7h9cQn6cNzi0QQoT9xY4v2nUy0

###Get Restaurant By ID

GET {{baseUrl}}/api/restaurants/1

###Create a new restaurant

POST {{baseUrl}}/api/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE4MDc0NTYsImV4cCI6MTc2MTgxMTA1Nn0.H8ELLmNAbUOMc-qpD7h9cQn6cNzi0QQoT9xY4v2nUy0

{
  "name": "The safari park",
  "description": "A cozy vegan restaurant with locally sourced ingredients.",
  "address": "12 Riverside Drive",
  "city": "Nairobi",
  "phone_number": "+254700111222",
  "email": "info@safaripark.co.ke",
  "opening_time": "09:00:00",
  "closing_time": "23:00:00",
  "cuisine_type": "italian"
}

###Update an existing restaurant

PUT {{baseUrl}}/api/restaurants/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE4MDc0NTYsImV4cCI6MTc2MTgxMTA1Nn0.H8ELLmNAbUOMc-qpD7h9cQn6cNzi0QQoT9xY4v2nUy0

{
  "name": "Cafe Bliss Updated",
  "description": "Now serving brunch and fresh pastries.",
  "address": "123 Main Street",
  "city": "Nairobi",
  "phone_number": "+254711223344",
  "email": "contact@cafebliss.co.ke",
  "opening_time": "07:00:00",
  "closing_time": "21:00:00",
  "cuisine_type": "Cafe",
  "is_active": true
}


###Delete a restaurant

DELETE {{baseUrl}}/api/restaurants/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE4MDc0NTYsImV4cCI6MTc2MTgxMTA1Nn0.H8ELLmNAbUOMc-qpD7h9cQn6cNzi0QQoT9xY4v2nUy0



### get all orderitem
GET {{baseUrl}}/api/OrderItem

### get orderitem by id
GET {{baseUrl}}/api/OrderItem/10

### create  orderitem
POST {{baseUrl}}/api/OrderItem
Content-Type: application/json

{
 

 "order_id": "2",
  "menu_item_id": "7",
  "quantity": "3",
  "unit_price": "10.12",
  "total_price": "30"
}

### Update OrderItem
PUT {{baseUrl}}/api/OrderItem/44
Content-Type: application/json

{
  
  "order_id": "2",
  "menu_item_id": "6",
  "quantity": "3",
  "unit_price": "10.12",
  "total_price": "30"
}


### Delete orderitem 
DELETE {{baseUrl}}/api/OrderItem/6


//menuitem endpoint

### get all MenuItem
GET {{baseUrl}}/api/MenuItem

### get MenuItem by id
GET {{baseUrl}}/api/MenuItem/6

### Create MenuItem
POST {{baseUrl}}/api/MenuItem
Content-Type: application/json

{
  "restaurant_id": "2",
  "category_id": "3",
  "name": "piza",
  "description": "its sweet",
  "price": "20.10",
  "is_available": "1"
}


### update  MenuItem
PuT {{baseUrl}}/api/MenuItem/7

{
     "restaurant_id": "2",
  "category_id": "3",
  "name": "piza",
  "description": "its sweet",
  "price": "20.10",
  "is_available": "1"
}

### Delete MenuItem 
DELETE {{baseUrl}}/api/MenuItem/9

