
# Base URL
@baseUrl = http://localhost:3000

### Root endpoint
GET {{baseUrl}}/


###
GET {{baseUrl}}/api


# ======AUTH TESTING ENDPOINTS=====

### Create a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john@example.com",
  "phone_number": "0712345678",
  "password": "123456",
  "user_type": "customer"
  "first_name": "Micheal",
  "last_name": "Ngigi",
  "email": "Micheal@outlook.com",
  "phone_number": "07973470830",
  "password": "adminpass",
  "user_type": "admin"
  
}

### Admin Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
  "email": "Micheal@outlook.com",
  "password": "adminpass"
}

### user login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "denis@gmail.com",
  "password": "password123"
}



### Update user
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "first_name": "denis",
  "last_name": "kathuri",
  "email": "denis@gmail.com",
  "phone_number": "0723356478",
  "password": "password123"
}

### Get user by ID
GET {{baseUrl}}/api/users/2



### Delete user
DELETE {{baseUrl}}/api/users/5

###Restaurant checking End points

###Get all Restaurants

GET {{baseUrl}}/api/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTI3ODYsImV4cCI6MTc2MTkxNjM4Nn0.pubbOQAs2tiO3FDkS0bI2DU2QKxglZVb7PneoXaqd8o

###Get Restaurant By ID

GET {{baseUrl}}/api/restaurants/1

###Create a new restaurant

POST {{baseUrl}}/api/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTI3ODYsImV4cCI6MTc2MTkxNjM4Nn0.pubbOQAs2tiO3FDkS0bI2DU2QKxglZVb7PneoXaqd8o

{
  "name": "The safari park",
  "description": "A cozy vegan restaurant with locally sourced ingredients.",
  "address": "12 Riverside Drive",
  "city": "Nairobi",
  "phone_number": "+254700111222",
  "email": "info@safaripark.co.ke",
  "opening_time": "09:00:00",
  "closing_time": "23:00:00",
  "cuisine_type": "italian"
}

###Update an existing restaurant

PUT {{baseUrl}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTI3ODYsImV4cCI6MTc2MTkxNjM4Nn0.pubbOQAs2tiO3FDkS0bI2DU2QKxglZVb7PneoXaqd8o

{
  "name": "Cafe Bliss Updated",
  "description": "Now serving brunch and fresh pastries.",
  "address": "123 Main Street",
  "city": "Nairobi",
  "phone_number": "+254711223344",
  "email": "contact@cafebliss.co.ke",
  "opening_time": "07:00:00",
  "closing_time": "21:00:00",
  "cuisine_type": "Cafe",
  "is_active": true
}


###Delete a restaurant

DELETE {{baseUrl}}/api/restaurants/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJmaXJzdF9uYW1lIjoiTWljaGVhbCIsImxhc3RfbmFtZSI6Ik5naWdpIiwiZW1haWwiOiJNaWNoZWFsQG91dGxvb2suY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTI3ODYsImV4cCI6MTc2MTkxNjM4Nn0.pubbOQAs2tiO3FDkS0bI2DU2QKxglZVb7PneoXaqd8o


//========ENDPOINTS FOR ORDERS=========

###  Get all orders
GET {{baseUrl}}/api/orders


###  Get order by ID
GET {{baseUrl}}/api/orders/2


### Create new order
POST {{baseUrl}}/api/orders
Content-Type: application/json

{
  "restaurant_id": 3,
  "customer_id": 1,
  "order_type": "food",
  "status": "Pending",
  "total_amount": 1800
}


###  Update order
PUT {{baseUrl}}/api/orders/1
Content-Type: application/json

{
    "customer_id": 1,
  "order_type": "Pickup",
  "status": "Completed",
  "total_amount": 950
}

### get all orderitem
GET {{baseUrl}}/api/OrderItem

### get orderitem by id
GET {{baseUrl}}/api/OrderItem/10

### create  orderitem
POST {{baseUrl}}/api/OrderItem
Content-Type: application/json

{
 

 "order_id": "2",
  "menu_item_id": "7",
  "quantity": "3",
  "unit_price": "10.12",
  "total_price": "30"
}

### Update OrderItem
PUT {{baseUrl}}/api/OrderItem/44
Content-Type: application/json

{
  
  "order_id": "2",
  "menu_item_id": "6",
  "quantity": "3",
  "unit_price": "10.12",
  "total_price": "30"
}
###  Delete order
DELETE {{baseUrl}}/api/orders/1


### Delete orderitem 
DELETE {{baseUrl}}/api/OrderItem/6



### get all MenuItem
GET {{baseUrl}}/api/MenuItem

### get MenuItem by id
GET {{baseUrl}}/api/MenuItem/6

### Create MenuItem
POST {{baseUrl}}/api/MenuItem
Content-Type: application/json

{
  "restaurant_id": "2",
  "category_id": "3",
  "name": "piza",
  "description": "its sweet",
  "price": "20.10",
  "is_available": "1"
}


### update  MenuItem
PuT {{baseUrl}}/api/MenuItem/7

{
     "restaurant_id": "2",
  "category_id": "3",
  "name": "piza",
  "description": "its sweet",
  "price": "20.10",
  "is_available": "1"
}

### Delete MenuItem 
DELETE {{baseUrl}}/api/MenuItem/9

# =======================
#      CATEGORIES ENDPOINTS
# =======================

###  Get all categories
GET {{baseUrl}}/api/categories

###  Get category by ID
GET {{baseUrl}}/api/categories/3

### Create new category
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "restaurant_id": 2,
  "name": "Beverages",
  "description": "Soft drinks and juices",
  "is_active": true
}

###  Update category
PUT {{baseUrl}}/api/categories/1
Content-Type: application/json

{
  "restaurant_id": 2,
  "name": "Hot Beverages",
  "description": "Coffee and tea",
  "is_active": true
}

###  Delete category
DELETE {{baseUrl}}/api/categories/1
